apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base # ベースとなるマニフェストの場所

images:
  - name: back-image # ここは変更しない
    newTag: 1.0.1 # アプリケーションのバージョン番号
    newName: 960136813215.dkr.ecr.ap-northeast-1.amazonaws.com/hiyoko/back:1.0.0 # ECRレジストリのURI
