apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-config
data:
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: "true"
  RDS_HOSTNAME: eks-work-db.cvoszqnu8tok.ap-northeast-1.rds.amazonaws.com
  RDS_DB_NAME: myworkdb
  RDS_USERNAME: mywork
  RDS_PASSWORD: 3;nUso0M3YdI5p:,